// dna.js — DNA raw data import: parser, storage, context assembly
// Parses raw DNA files from Ancestry, 23andMe, MyHeritage, FTDNA, Living DNA
// Runs the heavy parsing in a Web Worker (inline blob) to keep UI responsive

import { state } from './state.js';
import { escapeHTML, showNotification } from './utils.js';
import { saveImportedData } from './data.js';

// ═══════════════════════════════════════════════
// FORMAT DETECTION
// ═══════════════════════════════════════════════

// Detect DNA file by checking first few lines of text content
export function detectDNAFile(text) {
  const first = text.slice(0, 1500);
  if (first.startsWith('#AncestryDNA')) return 'ancestry';
  if (first.includes('generated by 23andMe')) {
    // 23andMe Mito/Y files have the same header (~900 bytes) — need 1500 bytes to see data lines
    // Filter out truncated trailing line from the byte slice
    const dataLines = first.split(/\r?\n/).filter(l => l.trim() && !l.startsWith('#') && (l.match(/\t/g) || []).length >= 3);
    if (dataLines.length > 0 && dataLines.every(l => /^\S+\tMT\t/.test(l))) return '23andme-mito';
    if (dataLines.length > 0 && dataLines.every(l => /^\S+\tY\t/.test(l))) return '23andme-y';
    return '23andme';
  }
  if (first.includes('# Living DNA customer genotype data download file version')) return 'livingdna';
  // Illumina GenomeStudio export (DNAEra and other clinical labs running Illumina arrays):
  // BOM-prefixed [Header] block with GSGT Version, then [Data] block with comma-separated
  // "Sample Name,SNP Name,Chr,Position,Allele1 - Plus,Allele2 - Plus" rows.
  if (first.includes('GSGT Version,')) return 'illumina-gsgt';
  // CSV formats — no comment lines, start with header
  const firstLine = first.split(/\r?\n/)[0].trim();
  if (/^RSID,CHROMOSOME,POSITION,RESULT$/i.test(firstLine)) return 'csv'; // MyHeritage or FTDNA
  if (/^"?RSID"?,/i.test(firstLine)) return 'csv'; // quoted variant
  // Tab-separated: rsid\tchromosome\tposition\tgenotype (23andMe without header, or stripped)
  if (/^rsid\tchromosome\tposition\tgenotype/i.test(firstLine)) return '23andme';
  // Headerless: lines starting with rs followed by tab-separated fields (rsid\tchr\tpos\tAA)
  const dataLines = first.split(/\r?\n/).filter(l => l.trim() && !l.startsWith('#'));
  if (dataLines.length > 0 && /^rs\d+\t\d+\t\d+\t[ACGT\-]{1,2}$/i.test(dataLines[0].trim())) return '23andme';
  // mtDNA CSV: short files with position+allele lines like "263G", "10398G"
  if (dataLines.length > 0 && dataLines.length < 200 && dataLines.filter(l => /^\d+[ACGT]$/i.test(l.trim())).length >= dataLines.length * 0.8) return 'mtdna';
  return null;
}

// Check if a dropped/selected file looks like a DNA raw data file (by name only — sync check)
export function isDNAFile(file) {
  if (!file) return false;
  const name = file.name.toLowerCase();
  // Common DNA file patterns
  if (name.includes('ancestrydna')) return true;
  if (name.includes('23andme')) return true;
  if (name.includes('myheritage') && name.includes('dna')) return true;
  if (name.includes('family_finder')) return true;
  if (name.includes('livingdna') || name.includes('living_dna')) return true;
  if (name.includes('genome') || name.includes('genotype') || name.includes('raw_dna') || name.includes('rawdna')) return true;
  if (name.includes('mtdna') || name.includes('mt-dna') || name.includes('mt_dna')) return true;
  if (name.includes('dnaera')) return true;
  return false;
}

// Content-based DNA detection — reads first 1500 bytes (async, needs to see past 23andMe header)
export async function isDNAFileByContent(file) {
  try {
    const header = await file.slice(0, 1500).text();
    return detectDNAFile(header) !== null;
  } catch { return false; }
}

// ═══════════════════════════════════════════════
// WEB WORKER PARSER (inline blob)
// ═══════════════════════════════════════════════

const WORKER_CODE = `
// DNA parser worker — receives { file, snpIds, format }
// Posts back { matches, source, totalLines, format }

self.onmessage = async function(e) {
  const { file, snpIds, format } = e.data;
  const text = await file.text();
  const lines = text.split(/\\r?\\n/);
  const lookupSet = new Set(snpIds);
  const matches = {};
  let totalData = 0;
  let detectedFormat = format;
  // Illumina GSGT files have a [Header] block that must be skipped — flip
  // this true once we hit [Data] and discard the column-header line that
  // follows it.
  let illuminaInData = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line || line.startsWith('#')) continue;

    // Skip header lines
    const upper = line.toUpperCase();
    if (upper.startsWith('RSID') || upper.startsWith('"RSID')) continue;

    let rsid, genotype;

    if (detectedFormat === 'illumina-gsgt') {
      // Walk the [Header] block until [Data], then skip the column-header
      // line ("Sample Name,SNP Name,Chr,Position,Allele1 - Plus,Allele2 - Plus")
      // before any rows are eligible.
      const trimmed = line.trim();
      if (!illuminaInData) {
        if (/^\[Data\]/i.test(trimmed)) illuminaInData = true;
        continue;
      }
      if (/^Sample Name/i.test(trimmed)) continue;
      const parts = trimmed.split(',');
      if (parts.length < 6) continue;
      rsid = parts[1].trim();           // SNP Name
      // Illumina probes wrap rsids many ways: seq-rs1234, GSA-rs1234,
      // ilmnseq_rs1234_ilmnTOP_5AT, BOT-rs1234, dup-seq-rs1234, etc.
      // Extract the bare rsid so a wrapped probe still hits the lookup.
      const m = rsid.match(/(rs\\d+)/);
      if (m) rsid = m[1];
      const a1 = parts[4].trim();        // Allele1 - Plus
      const a2 = parts[5].trim();        // Allele2 - Plus
      if (a1 === '-' || a2 === '-' || a1 === '0' || a2 === '0') { totalData++; continue; }
      genotype = a1 + a2;
    } else if (detectedFormat === 'ancestry') {
      // Tab-separated: rsid, chromosome, position, allele1, allele2
      const parts = line.split('\\t');
      if (parts.length < 5) continue;
      rsid = parts[0].trim();
      const a1 = parts[3].trim();
      const a2 = parts[4].trim();
      if (a1 === '0' || a2 === '0' || a1 === '-' || a2 === '-') { totalData++; continue; }
      genotype = a1 + a2;
    } else if (detectedFormat === '23andme' || detectedFormat === 'livingdna') {
      // Tab-separated: rsid, chromosome, position, genotype
      const parts = line.split('\\t');
      if (parts.length < 4) continue;
      rsid = parts[0].trim();
      genotype = parts[3].trim();
      if (genotype === '--' || genotype === '00') { totalData++; continue; }
    } else if (detectedFormat === 'csv') {
      // Comma-separated: RSID, CHROMOSOME, POSITION, RESULT (possibly quoted)
      const parts = line.split(',').map(s => s.replace(/^"|"$/g, '').trim());
      if (parts.length < 4) continue;
      rsid = parts[0];
      genotype = parts[3];
      if (genotype === '--' || genotype === '00' || !genotype) { totalData++; continue; }
    } else {
      continue;
    }

    // Skip internal IDs (23andMe uses i-prefixed IDs for some markers)
    if (!rsid.startsWith('rs')) { totalData++; continue; }

    totalData++;

    if (lookupSet.has(rsid) && !matches[rsid]) {
      // First non-missing call wins. Illumina chips often have multiple
      // probes for the same SNP (seq-rsX + seq-rsX.1 + seq-rsX.2). They
      // usually agree, but if a later probe failed, keeping the first
      // valid call is safer than overwriting it.
      matches[rsid] = genotype;
    }
  }

  self.postMessage({ matches, source: detectedFormat, totalLines: totalData, format: detectedFormat });
};
`;

let _workerBlobUrl = null;

function createWorker() {
  if (!_workerBlobUrl) {
    const blob = new Blob([WORKER_CODE], { type: 'application/javascript' });
    _workerBlobUrl = URL.createObjectURL(blob);
  }
  return new Worker(_workerBlobUrl);
}

// ═══════════════════════════════════════════════
// PARSE DNA FILE
// ═══════════════════════════════════════════════

let _snpTable = null;
let _snpTablePromise = null;

function loadSNPTable() {
  if (_snpTable) return Promise.resolve(_snpTable);
  if (!_snpTablePromise) {
    _snpTablePromise = fetch('data/snp-health.json')
      .then(r => r.json())
      .then(data => { _snpTable = data; window._snpTableCache = data; return data; })
      .catch(err => { _snpTablePromise = null; if (window.isDebugMode?.()) console.error('Failed to load SNP table:', err); throw err; });
  }
  return _snpTablePromise;
}

// Eagerly load SNP table when genetics data exists (e.g. after JSON import)
export function ensureSNPTable() { if (state.importedData?.genetics) loadSNPTable(); }

// Returns { matches: { rsid: { genotype, gene, variant, effect, note } }, source, totalLines, coverage }
export async function parseDNAFile(file) {
  const snpTable = await loadSNPTable();
  const snpIds = Object.keys(snpTable).filter(k => k.startsWith('rs'));

  // Detect format from first chunk
  const headerChunk = await file.slice(0, 1000).text();
  const format = detectDNAFile(headerChunk);
  if (!format) throw new Error('Unrecognized DNA file format');

  // Run parser in a fresh worker (prevents handler conflicts on concurrent parses)
  const worker = createWorker();
  const result = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => { worker.terminate(); reject(new Error('DNA parsing timed out')); }, 30000);
    worker.onmessage = (e) => { clearTimeout(timeout); worker.terminate(); resolve(e.data); };
    worker.onerror = (e) => { clearTimeout(timeout); worker.terminate(); reject(new Error(e.message)); };
    worker.postMessage({ file, snpIds, format });
  });

  // Enrich matches with lookup table data
  const enriched = {};
  for (const [rsid, genotype] of Object.entries(result.matches)) {
    const entry = snpTable[rsid];
    if (!entry) continue;
    const reversed = genotype.length === 2 ? genotype[1] + genotype[0] : genotype;
    const genotypeInfo = entry.genotypes[genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(genotype)] || null;
    enriched[rsid] = {
      genotype,
      gene: entry.gene,
      variant: entry.variant,
      category: entry.category,
      markers: entry.markers || [],
      effect: genotypeInfo ? genotypeInfo.effect : 'unknown',
      note: genotypeInfo ? genotypeInfo.note : `Genotype ${genotype} not in lookup table`,
    };
  }

  return {
    matches: enriched,
    source: formatSourceName(result.source),
    totalLines: result.totalLines,
    coverage: { found: Object.keys(enriched).length, total: snpIds.length },
  };
}

// Sort alleles alphabetically for lookup (AG = GA)
function sortAlleles(genotype) {
  if (!genotype || genotype.length !== 2) return genotype;
  const sorted = genotype.split('').sort().join('');
  return sorted;
}

function formatSourceName(format) {
  const names = { ancestry: 'AncestryDNA', '23andme': '23andMe', livingdna: 'Living DNA', csv: 'MyHeritage/FTDNA', 'illumina-gsgt': 'Illumina GenomeStudio (DNAEra)' };
  return names[format] || format;
}

// ═══════════════════════════════════════════════
// APOE HAPLOTYPE RESOLUTION
// ═══════════════════════════════════════════════

// APOE is determined by two SNPs: rs429358 and rs7412
// rs429358 T→C = ε4 allele, rs7412 C→T = ε2 allele
// APOE haplotype from unphased genotypes — genotype-combination lookup
// Raw DNA files are UNPHASED (alleles aren't assigned to chromosomes),
// so we use the diploid genotype pair, not per-allele pairing.
// ε2: rs429358=T, rs7412=T | ε3: rs429358=T, rs7412=C | ε4: rs429358=C, rs7412=C
function resolveAPOE(matches) {
  const g429 = matches.rs429358?.genotype;
  const g7412 = matches.rs7412?.genotype;
  if (!g429 || !g7412 || g429.length !== 2 || g7412.length !== 2) return null;
  const key = `${sortAlleles(g429)}|${sortAlleles(g7412)}`;
  const table = {
    'TT|CC': '\u03B53/\u03B53', 'CT|CC': '\u03B53/\u03B54', 'CC|CC': '\u03B54/\u03B54',
    'TT|CT': '\u03B52/\u03B53', 'CT|CT': '\u03B52/\u03B54', 'TT|TT': '\u03B52/\u03B52',
  };
  return table[key] || null;
}

// ═══════════════════════════════════════════════
// STORAGE
// ═══════════════════════════════════════════════

export function saveGeneticsData(profileData, parseResult) {
  // Count effects for quick display (avoids needing SNP table at render time)
  const apoe = resolveAPOE(parseResult.matches);
  const apoeRsids = apoe ? new Set(['rs429358', 'rs7412']) : new Set();
  let significant = 0, moderate = 0, normal = 0;
  for (const [rsid, data] of Object.entries(parseResult.matches)) {
    if (apoeRsids.has(rsid)) continue;
    if (data.effect === 'significant') significant++;
    else if (data.effect === 'moderate') moderate++;
    else if (data.effect === 'none') normal++;
  }
  profileData.genetics = {
    source: parseResult.source,
    importDate: new Date().toISOString().slice(0, 10),
    coverage: parseResult.coverage,
    effects: { significant, moderate, normal },
    snps: {},
  };
  for (const [rsid, data] of Object.entries(parseResult.matches)) {
    profileData.genetics.snps[rsid] = {
      genotype: data.genotype,
      gene: data.gene,
      variant: data.variant,
    };
  }
  if (apoe) {
    profileData.genetics.apoe = apoe;
  }
}

export function deleteGeneticsData(profileData) {
  delete profileData.genetics;
}

// ═══════════════════════════════════════════════
// CONTEXT ASSEMBLY
// ═══════════════════════════════════════════════

// Build genetics context string for AI — only non-"none" effects, relevant to current markers
export function buildGeneticsContext(genetics, activeMarkerKeys) {
  if (!genetics) return '';
  if (!genetics.snps && !genetics.mtdna) return '';

  const lines = [];

  // mtDNA haplogroup — always include when present
  if (genetics.mtdna) {
    const mt = genetics.mtdna;
    const cLabel = mt.coupling ? mt.coupling.label : 'coupling unknown';
    lines.push(`mtDNA Haplogroup: ${mt.haplogroup} (${cLabel})`);
    if (mt.coupling) {
      const mismatch = detectMtDNAMismatch(genetics);
      if (mismatch && mismatch.mismatch) {
        lines.push(`ENVIRONMENT MISMATCH: ${mismatch.message}`);
        if (mismatch.implications) lines.push(`Implications: ${mismatch.implications}`);
      } else if (mismatch && !mismatch.mismatch) {
        lines.push(mismatch.message);
      }
    }
  }

  // APOE haplotype — always include
  if (genetics.apoe) {
    lines.push(`APOE: ${genetics.apoe}`);
  }

  const snpTable = _snpTable;
  if (!snpTable || !genetics.snps) {
    if (lines.length === 0) return '';
    const parts = [];
    if (genetics.mtdna) parts.push(`mtDNA ${genetics.mtdna.haplogroup}`);
    if (genetics.source) parts.push(genetics.source);
    return `GENETICS (${parts.join(', ')}):\n${lines.map(l => '- ' + l).join('\n')}`;
  }

  // Group SNPs by category — skip raw APOE component SNPs (haplotype shown instead)
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  const byCategory = {};
  for (const [rsid, stored] of Object.entries(genetics.snps)) {
    if (genetics.apoe && apoeRsids.has(rsid)) continue; // haplotype covers these
    const entry = snpTable[rsid];
    if (!entry) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const genotypeInfo = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!genotypeInfo || genotypeInfo.effect === 'none') continue;

    // Filter to SNPs relevant to active markers (if provided)
    if (activeMarkerKeys && activeMarkerKeys.length > 0) {
      const hasRelevantMarker = (entry.markers || []).some(m => activeMarkerKeys.includes(m));
      if (!hasRelevantMarker) continue;
    }

    const cat = entry.category || 'other';
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(`${stored.gene} ${stored.variant}: ${stored.genotype} — ${genotypeInfo.note}`);
  }

  for (const [cat, entries] of Object.entries(byCategory)) {
    lines.push(...entries);
  }

  if (lines.length === 0) return '';
  const headerParts = [];
  if (genetics.source) headerParts.push(genetics.source);
  if (genetics.snps) headerParts.push(`${Object.keys(genetics.snps).length} SNPs`);
  if (genetics.mtdna) headerParts.push(`mtDNA ${genetics.mtdna.haplogroup}`);
  return `GENETICS (${headerParts.join(', ')}):\n${lines.map(l => '- ' + l).join('\n')}`;
}

// Full genetics dump for when user explicitly asks about genetics
export function buildFullGeneticsContext(genetics) {
  return buildGeneticsContext(genetics, null); // no marker filter = include all non-none
}

// ═══════════════════════════════════════════════
// DASHBOARD SECTION
// ═══════════════════════════════════════════════

export function renderGeneticsSection() {
  const genetics = state.importedData.genetics;
  const hasSnps = genetics && genetics.snps && Object.keys(genetics.snps).length > 0;
  const hasMtdna = genetics && genetics.mtdna;
  if (!hasSnps && !hasMtdna) return '';
  if (hasSnps && !_snpTable) {
    loadSNPTable().then(() => { if (window.navigate) window.navigate('dashboard'); });
    return '';
  }
  const snpTable = _snpTable;
  const snpCount = hasSnps ? Object.keys(genetics.snps).length : 0;
  const apoe = genetics.apoe;
  const collapsed = localStorage.getItem('labcharts-genetics-collapsed') === '1';

  // Group findings by category, skip "none"
  const byCat = {};
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  for (const [rsid, stored] of Object.entries(genetics.snps || {})) {
    if (apoe && apoeRsids.has(rsid)) continue;
    const entry = snpTable?.[rsid];
    if (!entry) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const info = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!info || info.effect === 'none') continue;
    const cat = entry.category || 'other';
    if (!byCat[cat]) byCat[cat] = [];
    byCat[cat].push({ rsid, gene: stored.gene, variant: stored.variant, genotype: stored.genotype, effect: info.effect, valence: info.valence || 'risk', note: info.note, references: entry.references || [] });
  }

  // Sort categories: those with significant findings first
  const catOrder = Object.entries(byCat).sort(([, a], [, b]) => {
    const aS = a.some(f => f.effect === 'significant') ? 0 : 1;
    const bS = b.some(f => f.effect === 'significant') ? 0 : 1;
    return aS - bS;
  });
  const totalFindings = catOrder.reduce((n, [, fs]) => n + fs.length, 0);

  // Two-axis dot: severity x valence. Protective = green regardless of magnitude;
  // neutral = white circle (lab-artifact / informational, neither bad nor good).
  // Risk severity scales by warmth (significant -> red, moderate -> yellow, mild -> orange).
  const dotFor = (effect, valence) => {
    if (effect === 'none') return '';
    if (valence === 'protective') return '\uD83D\uDFE2';
    if (valence === 'neutral') return '\u26AA';
    if (effect === 'significant') return '\uD83D\uDD34';
    if (effect === 'moderate') return '\uD83D\uDFE1';
    if (effect === 'mild') return '\uD83D\uDFE0';
    return '';
  };
  const catLabels = { methylation: 'Methylation', iron: 'Iron', lipids: 'Lipids', vitaminD: 'Vitamin D', vitaminB12: 'Vitamin B12', bilirubin: 'Bilirubin', thyroid: 'Thyroid', fattyAcids: 'Fatty Acids', bloodSugar: 'Blood Sugar', sexHormones: 'Sex Hormones', alcohol: 'Alcohol', caffeine: 'Caffeine', bodyComposition: 'Body Composition' };

  const metaParts = [];
  if (genetics.source) metaParts.push(escapeHTML(genetics.source));
  if (hasSnps) metaParts.push(`${snpCount} SNPs`);
  if (hasMtdna) metaParts.push(`mtDNA ${escapeHTML(genetics.mtdna.haplogroup)}`);
  if (totalFindings > 0) metaParts.push(`${totalFindings} findings`);
  const latestDate = [genetics.importDate, genetics.mtdna?.importDate].filter(Boolean).sort().pop();
  if (latestDate) metaParts.push(latestDate);

  let html = `<div class="dashboard-section genetics-section" id="genetics-section">
    <div class="section-header" onclick="toggleGeneticsCollapse()" style="cursor:pointer">
      <span>\uD83E\uDDEC Genetics</span>
      <span class="section-meta">${metaParts.join(' \u00B7 ')}
        <span class="genetics-collapse-arrow${collapsed ? ' collapsed' : ''}">\u25BE</span></span>
    </div>`;

  html += `<div class="genetics-body${collapsed ? ' hidden' : ''}">`;

  // mtDNA Haplogroup — prominent display
  if (hasMtdna) {
    const mt = genetics.mtdna;
    const mismatch = detectMtDNAMismatch(genetics);
    html += `<div class="genetics-mtdna">
      <div class="genetics-mtdna-hg"><span class="genetics-mtdna-label">mtDNA Haplogroup:</span> <strong>${escapeHTML(mt.haplogroup)}</strong></div>`;
    if (mt.coupling) {
      html += `<div class="genetics-mtdna-coupling">${escapeHTML(mt.coupling.label)} \u2014 ${escapeHTML(mt.coupling.climate)}</div>`;
    }
    if (mismatch && mismatch.mismatch) {
      html += `<div class="genetics-mtdna-mismatch mismatch-${mismatch.severity}">${escapeHTML(mismatch.message)}</div>`;
    } else if (mismatch && !mismatch.mismatch) {
      html += `<div class="genetics-mtdna-match">${escapeHTML(mismatch.message)}</div>`;
    }
    html += `<div class="genetics-mtdna-refs">Wallace 2015 (<a href="https://pubmed.ncbi.nlm.nih.gov/26406369/" target="_blank" rel="noopener">PMID: 26406369</a>)
      \u00B7 <a href="#" onclick="window.deleteMtDNAData();return false" style="color:var(--text-muted)">remove</a></div>`;
    html += `</div>`;
  }

  if (apoe) {
    html += `<div class="genetics-apoe">APOE: <strong>${escapeHTML(apoe)}</strong></div>`;
  }

  if (totalFindings > 0) {
    // Initially show first 8 findings, rest hidden behind "show all"
    let shown = 0;
    const INITIAL_LIMIT = 8;
    html += `<div class="genetics-findings">`;
    // Legend — explain the dot scheme so users can read severity AND valence at a glance.
    html += `<div class="genetics-legend" title="What the dots mean">
      <span><span class="genetics-legend-dot">🔴</span> significant risk</span>
      <span><span class="genetics-legend-dot">🟡</span> moderate risk</span>
      <span><span class="genetics-legend-dot">🟠</span> mild risk</span>
      <span><span class="genetics-legend-dot">🟢</span> beneficial</span>
      <span><span class="genetics-legend-dot">⚪</span> informational</span>
    </div>`;
    for (const [cat, findings] of catOrder) {
      // Sort significant first within category
      findings.sort((a, b) => (a.effect === 'significant' ? 0 : 1) - (b.effect === 'significant' ? 0 : 1));
      const catLabel = catLabels[cat] || cat;
      const startHidden = shown >= INITIAL_LIMIT;
      html += `<div class="genetics-cat-group${startHidden ? ' genetics-extra' : ''}">`;
      html += `<div class="genetics-cat-label">${escapeHTML(catLabel)}</div>`;
      for (const f of findings) {
        const isExtra = shown >= INITIAL_LIMIT;
        const refLink = f.references.length > 0 && /^https?:/.test(f.references[0]) ? ` <a href="${f.references[0].replace(/"/g, '&quot;')}" target="_blank" rel="noopener" class="detail-genetics-ref" title="Primary study (PubMed)">primary study</a>` : '';
        const snpediaLink = ` <a href="https://www.snpedia.com/index.php/${f.rsid.charAt(0).toUpperCase() + f.rsid.slice(1)}" target="_blank" rel="noopener" class="detail-genetics-ref" title="All studies (SNPedia)">more studies</a>`;
        html += `<div class="genetics-finding-row${isExtra && !startHidden ? ' genetics-extra' : ''}">
          <span>${dotFor(f.effect, f.valence)}</span>
          <span class="genetics-finding-gene">${escapeHTML(f.gene)} ${escapeHTML(f.variant)}</span>
          <span class="genetics-finding-genotype">${escapeHTML(f.genotype)}</span>
          <span class="genetics-finding-note">${escapeHTML(f.note)}${refLink}${snpediaLink}</span>
        </div>`;
        shown++;
      }
      html += `</div>`;
    }
    if (totalFindings > INITIAL_LIMIT) {
      html += `<button class="genetics-show-all" onclick="toggleGeneticsExpand(this)">${totalFindings - INITIAL_LIMIT} more findings</button>`;
    }
    html += `</div>`;
  }

  html += `<div class="genetics-actions">
    <label class="genetics-action-link" onclick="reimportDNA()">Re-import</label>
    <label class="genetics-action-link genetics-action-delete" onclick="window.confirmDeleteDNA()">Delete</label>
  </div>`;
  html += `</div></div>`;

  return html;
}

function toggleGeneticsCollapse() {
  const body = document.querySelector('.genetics-body');
  const arrow = document.querySelector('.genetics-collapse-arrow');
  if (!body) return;
  const isHidden = body.classList.toggle('hidden');
  arrow?.classList.toggle('collapsed', isHidden);
  localStorage.setItem('labcharts-genetics-collapsed', isHidden ? '1' : '0');
}

function toggleGeneticsExpand(btn) {
  const container = document.querySelector('.genetics-findings');
  if (!container) return;
  const isExpanded = container.classList.toggle('expanded');
  if (!btn.dataset.label) btn.dataset.label = btn.textContent;
  btn.textContent = isExpanded ? 'Show less' : btn.dataset.label;
}

function reimportDNA() {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.txt,.csv';
  input.onchange = (e) => {
    const file = e.target.files?.[0];
    if (file && window.handleDNAFile) window.handleDNAFile(file);
  };
  input.click();
}

// ═══════════════════════════════════════════════
// IMPORT FLOW
// ═══════════════════════════════════════════════

let _dnaImportRunning = false;

export async function handleDNAFile(file) {
  if (_dnaImportRunning) { showNotification('DNA import already in progress', 'info'); return; }
  if (window.isImportRunning && window.isImportRunning()) { showNotification('Lab import in progress — wait for it to finish', 'info'); return; }
  _dnaImportRunning = true;
  try {
    showNotification('Parsing DNA file...', 'info');
    const result = await parseDNAFile(file);
    if (Object.keys(result.matches).length === 0) {
      showNotification('No health-relevant SNPs found in this file. Is it a DNA raw data export?', 'error');
      _dnaImportRunning = false;
      return;
    }
    showDNAImportPreview(result, file.name);
  } catch (e) {
    if (window.isDebugMode?.()) console.error('DNA import error:', e);
    showNotification(e.message || 'Failed to parse DNA file', 'error');
    _dnaImportRunning = false;
  }
}

function showDNAImportPreview(result, fileName) {
  window._pendingDNAImport = result;

  // Categorize matches by effect — skip raw APOE components when haplotype resolved
  const apoe = resolveAPOE(result.matches);
  const apoeRsids = apoe ? new Set(['rs429358', 'rs7412']) : new Set();
  const significant = [], moderate = [], none = [], unknown = [];
  for (const [rsid, m] of Object.entries(result.matches)) {
    if (apoeRsids.has(rsid)) continue;
    const item = { rsid, ...m };
    if (m.effect === 'significant') significant.push(item);
    else if (m.effect === 'moderate') moderate.push(item);
    else if (m.effect === 'none') none.push(item);
    else unknown.push(item);
  }

  const effectIcon = { significant: '\uD83D\uDD34', moderate: '\uD83D\uDFE1', none: '\uD83D\uDFE2', unknown: '\u2753' };
  const effectLabel = { significant: 'Significant impact', moderate: 'Moderate impact', none: 'Normal / no impact', unknown: 'Not in lookup' };

  function renderGroup(items, label) {
    if (items.length === 0) return '';
    return `<div class="dna-preview-group">
      <div class="dna-preview-group-title">${label} (${items.length})</div>
      ${items.map(m => `<div class="dna-preview-row">
        <span class="dna-preview-icon">${effectIcon[m.effect] || '\u2753'}</span>
        <span class="dna-preview-gene">${escapeHTML(m.gene)} <span class="dna-preview-variant">${escapeHTML(m.variant)}</span></span>
        <span class="dna-preview-genotype">${escapeHTML(m.genotype)}</span>
      </div>
      <div class="dna-preview-note">${escapeHTML(m.note)}</div>`).join('')}
    </div>`;
  }

  function renderCollapsedGroup(items, label) {
    if (items.length === 0) return '';
    return `<div class="dna-preview-group">
      <div class="dna-preview-group-title dna-preview-collapsible" onclick="this.parentElement.classList.toggle('expanded')">
        ${label} (${items.length}) <span class="dna-preview-expand-hint">show</span>
      </div>
      <div class="dna-preview-collapsed-items">
        ${items.map(m => `<div class="dna-preview-row">
          <span class="dna-preview-icon">${effectIcon[m.effect] || '\u2753'}</span>
          <span class="dna-preview-gene">${escapeHTML(m.gene)} <span class="dna-preview-variant">${escapeHTML(m.variant)}</span></span>
          <span class="dna-preview-genotype">${escapeHTML(m.genotype)}</span>
        </div>`).join('')}
      </div>
    </div>`;
  }

  const html = `
    <div class="dna-preview-header">
      <div class="dna-preview-title">DNA Import \u2014 ${escapeHTML(result.source)}</div>
      <div class="dna-preview-stats">${result.totalLines.toLocaleString()} SNPs scanned \u00B7 ${result.coverage.found} of ${result.coverage.total} health-relevant SNPs found</div>
      ${apoe ? `<div class="dna-preview-apoe">APOE Haplotype: <strong>${escapeHTML(apoe)}</strong></div>` : ''}
    </div>
    <div class="dna-preview-body">
      ${renderGroup(significant, '\uD83D\uDD34 Significant findings')}
      ${renderGroup(moderate, '\uD83D\uDFE1 Moderate findings')}
      ${renderCollapsedGroup(none, '\uD83D\uDFE2 Normal')}
      ${renderCollapsedGroup(unknown, '\u2753 Genotype not in lookup')}
    </div>
    <div class="dna-preview-disclaimer">
      Processed locally \u2014 your DNA file was never transmitted. Only matched SNPs are stored.
    </div>
    <div class="dna-preview-actions">
      <button class="import-btn import-btn-secondary" onclick="closeDNAImportPreview()">Cancel</button>
      <button class="import-btn import-btn-primary" onclick="confirmDNAImport()">Import ${result.coverage.found} SNPs</button>
    </div>`;

  // Use a dedicated overlay — don't clobber the PDF import modal
  let overlay = document.getElementById('dna-modal-overlay');
  if (!overlay) {
    overlay = document.createElement('div');
    overlay.id = 'dna-modal-overlay';
    overlay.className = 'modal-overlay';
    document.body.appendChild(overlay);
  }
  overlay.innerHTML = `<div class="modal dna-preview-modal" role="dialog">${html}</div>`;
  overlay.classList.add('show');
}

function closeDNAImportPreview() {
  window._pendingDNAImport = null;
  _dnaImportRunning = false;
  const overlay = document.getElementById('dna-modal-overlay');
  if (overlay) overlay.classList.remove('show');
}

function confirmDNAImport() {
  const result = window._pendingDNAImport;
  if (!result) return;
  saveGeneticsData(state.importedData, result);
  saveImportedData();
  window._pendingDNAImport = null;
  _dnaImportRunning = false;
  const overlay = document.getElementById('dna-modal-overlay');
  if (overlay) overlay.classList.remove('show');
  showNotification(`Imported ${result.coverage.found} SNPs from ${result.source}`, 'success');

  // Build summary for chat confirmation
  const apoe = state.importedData.genetics?.apoe;
  const apoeRsids = apoe ? new Set(['rs429358', 'rs7412']) : new Set();
  let sigCount = 0, modCount = 0, normCount = 0;
  for (const [rsid, m] of Object.entries(result.matches)) {
    if (apoeRsids.has(rsid)) continue;
    if (m.effect === 'significant') sigCount++;
    else if (m.effect === 'moderate') modCount++;
    else if (m.effect === 'none') normCount++;
  }
  const parts = [];
  if (apoe) parts.push(`APOE: <strong>${escapeHTML(apoe)}</strong>`);
  if (sigCount > 0) parts.push(`\uD83D\uDD34 ${sigCount} significant`);
  if (modCount > 0) parts.push(`\uD83D\uDFE1 ${modCount} moderate`);
  if (normCount > 0) parts.push(`\uD83D\uDFE2 ${normCount} normal`);

  // Update chat onboarding — replace DNA upload with confirmation
  const dnaEl = document.querySelector('.chat-onboard-dna');
  if (dnaEl) {
    dnaEl.style.borderTop = '1px solid var(--border)';
    dnaEl.style.paddingTop = '12px';
    dnaEl.style.marginTop = '12px';
    dnaEl.innerHTML = `<p style="margin:0 0 6px">\uD83E\uDDEC <strong>${result.coverage.found} SNPs imported</strong> from ${escapeHTML(result.source)}</p>
      <div style="font-size:13px;line-height:1.8">${parts.join(' &nbsp;\u00B7&nbsp; ')}</div>
      <div style="font-size:12px;color:var(--text-muted);margin-top:6px">I'll factor these into all your lab interpretations.</div>`;
  } else if (window.updateChatNudge) {
    window.updateChatNudge();
  }

  // Refresh dashboard
  if (window.navigate) window.navigate('dashboard');
}

// ═══════════════════════════════════════════════
// DETAIL MODAL HELPER
// ═══════════════════════════════════════════════

// Get SNPs relevant to a specific marker dotKey (e.g. "coagulation.homocysteine")
function getRelevantSNPs(dotKey) {
  const genetics = state.importedData.genetics;
  if (!genetics || !genetics.snps || !_snpTable) return [];
  const results = [];
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  for (const [rsid, stored] of Object.entries(genetics.snps)) {
    if (genetics.apoe && apoeRsids.has(rsid)) continue;
    const entry = _snpTable[rsid];
    if (!entry || !entry.markers) continue;
    if (!entry.markers.includes(dotKey)) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const info = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!info) continue;
    results.push({ rsid, gene: stored.gene, variant: stored.variant, genotype: stored.genotype, effect: info.effect, note: info.note, references: entry.references || [] });
  }
  const order = { significant: 0, moderate: 1, none: 2 };
  results.sort((a, b) => (order[a.effect] ?? 3) - (order[b.effect] ?? 3));
  return results;
}

// ═══════════════════════════════════════════════
// mtDNA HAPLOGROUP SUPPORT
// ═══════════════════════════════════════════════

let _haplogroupTable = null;
let _haplogroupTablePromise = null;

function loadHaplogroupTable() {
  if (_haplogroupTable) return Promise.resolve(_haplogroupTable);
  if (!_haplogroupTablePromise) {
    _haplogroupTablePromise = fetch('data/haplogroups.json')
      .then(r => r.json())
      .then(data => { _haplogroupTable = data; return data; })
      .catch(err => { _haplogroupTablePromise = null; console.error('Failed to load haplogroup table:', err); throw err; });
  }
  return _haplogroupTablePromise;
}

export function ensureHaplogroupTable() {
  if (state.importedData?.genetics?.mtdna) loadHaplogroupTable();
}

function parseMtDNAMutations(text) {
  const mutations = [];
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    // Format 1: simple "263G" mutation notation (CSV export)
    const match = trimmed.match(/^(\d+)([ACGT])$/i);
    if (match) { mutations.push({ position: parseInt(match[1]), allele: match[2].toUpperCase(), raw: match[1] + match[2].toUpperCase() }); continue; }
    // Format 2: 23andMe tab-separated "rsid\tMT\tposition\tallele"
    const cols = trimmed.split('\t');
    if (cols.length >= 4 && cols[1] === 'MT') {
      const pos = parseInt(cols[2]);
      const allele = cols[3].trim().toUpperCase();
      if (pos > 0 && /^[ACGT]$/.test(allele)) mutations.push({ position: pos, allele, raw: pos + allele });
    }
  }
  return mutations;
}

function resolveHaplogroup(mutations, hapTable) {
  const mutationSet = new Set(mutations.map(m => m.raw));
  let bestMatch = null;
  let bestScore = 0;

  for (const [hg, data] of Object.entries(hapTable.haplogroups)) {
    if (data.isReference) continue; // H is reference — handle separately
    const diag = data.mutations;
    const matched = diag.filter(m => mutationSet.has(m));
    const score = matched.length / diag.length;
    if (score > bestScore && matched.length >= 2 && score >= 0.6) {
      bestScore = score;
      bestMatch = { haplogroup: hg, confidence: score, matchedMutations: matched.length, totalDiagnostic: diag.length };
    }
  }

  // Fallback: if no match, check for H (defined by ABSENCE of non-H markers)
  if (!bestMatch) {
    const nonHMarkers = ['7028T', '2706G', '10400T', '10398G', '489C'];
    const hasNonH = nonHMarkers.some(m => mutationSet.has(m));
    const hasUniversal = ['263G', '750G', '1438G', '4769G', '8860G', '15326G'].filter(m => mutationSet.has(m));
    if (!hasNonH && hasUniversal.length >= 3) {
      bestMatch = { haplogroup: 'H', confidence: 0.7, matchedMutations: hasUniversal.length, totalDiagnostic: 6 };
    }
  }

  return bestMatch;
}

function classifyCoupling(haplogroup, hapTable) {
  const hgData = hapTable.haplogroups[haplogroup];
  if (!hgData) return null;
  const couplingKey = hgData.coupling;
  const couplingData = hapTable.couplingLevels[couplingKey];
  if (!couplingData) return null;
  return {
    level: couplingKey,
    label: couplingData.label,
    shortLabel: couplingData.shortLabel,
    climate: hgData.climate,
    description: couplingData.description,
    implications: couplingData.implications,
    matchedLatBands: couplingData.latitudeBands
  };
}

export function detectMtDNAMismatch(genetics) {
  if (!genetics?.mtdna?.coupling) return null;
  const coupling = genetics.mtdna.coupling;

  // Get latitude band from profile
  const bandStr = window.getLatitudeFromLocation ? window.getLatitudeFromLocation() : null;
  if (!bandStr) return null;

  const BANDS = ['<25\u00b0 latitude (tropical)', '25-40\u00b0 (subtropical)', '40-50\u00b0 (temperate)', '50-60\u00b0 (northern)', '>60\u00b0 (subarctic)'];
  const bandIndex = BANDS.indexOf(bandStr);
  if (bandIndex === -1) return null;

  const bandNames = ['tropical', 'subtropical', 'temperate', 'northern', 'subarctic'];
  if (coupling.matchedLatBands.includes(bandIndex)) {
    return { mismatch: false, message: `mtDNA haplogroup ${genetics.mtdna.haplogroup} (${coupling.shortLabel}) is well-matched to your ${bandNames[bandIndex]} latitude.` };
  }

  const minBand = Math.min(...coupling.matchedLatBands);
  const maxBand = Math.max(...coupling.matchedLatBands);
  const distance = bandIndex < minBand ? minBand - bandIndex : bandIndex - maxBand;
  const severity = distance >= 2 ? 'significant' : 'moderate';

  return {
    mismatch: true,
    severity,
    message: `mtDNA haplogroup ${genetics.mtdna.haplogroup} (${coupling.shortLabel}) evolved for ${coupling.climate.toLowerCase()} climates, but you live at a ${bandNames[bandIndex]} latitude.`,
    implications: coupling.implications
  };
}

let _mtdnaImportRunning = false;

export async function handleMtDNAFile(file) {
  if (_mtdnaImportRunning) { showNotification('mtDNA import already in progress', 'info'); return; }
  _mtdnaImportRunning = true;
  try {
    const text = await file.text();
    const mutations = parseMtDNAMutations(text);
    if (mutations.length === 0) { showNotification('No mtDNA mutations found in this file', 'error'); _mtdnaImportRunning = false; return; }

    const hapTable = await loadHaplogroupTable();
    const resolved = resolveHaplogroup(mutations, hapTable);
    if (!resolved) { showNotification('Could not determine haplogroup — try a more complete mtDNA export', 'error'); _mtdnaImportRunning = false; return; }

    const coupling = classifyCoupling(resolved.haplogroup, hapTable);
    const hgData = hapTable.haplogroups[resolved.haplogroup];
    const source = file.name.toLowerCase().includes('23andme') || file.name.toLowerCase().includes('genome') ? 'mtDNA (23andMe)' : 'mtDNA CSV';
    window._pendingMtDNA = { mutations, resolved, coupling, hgData, source };
    _showMtDNAPreview(resolved, coupling, mutations, file.name);
  } catch (e) {
    if (window.isDebugMode?.()) console.error('mtDNA import error:', e);
    showNotification(e.message || 'Failed to parse mtDNA file', 'error');
  }
  _mtdnaImportRunning = false;
}

function _showMtDNAPreview(resolved, coupling, mutations, fileName) {
  const mismatch = coupling ? detectMtDNAMismatch({ mtdna: { haplogroup: resolved.haplogroup, coupling } }) : null;

  let html = `<div class="dna-preview-header">
    <div class="dna-preview-title">mtDNA Import</div>
    <div class="dna-preview-stats">${mutations.length} mutations from ${escapeHTML(fileName)}</div>
  </div>
  <div class="dna-preview-body">
    <div class="mtdna-preview-haplogroup">
      <div class="mtdna-hg-label">Haplogroup</div>
      <div class="mtdna-hg-value">${escapeHTML(resolved.haplogroup)}</div>
      <div class="mtdna-hg-confidence">${resolved.matchedMutations}/${resolved.totalDiagnostic} diagnostic mutations matched (${Math.round(resolved.confidence * 100)}%)</div>
    </div>`;
  if (coupling) {
    html += `<div class="mtdna-preview-coupling">
      <div class="mtdna-coupling-label">${escapeHTML(coupling.label)}</div>
      <div class="mtdna-coupling-climate">${escapeHTML(coupling.climate)}</div>
      <div class="mtdna-coupling-desc">${escapeHTML(coupling.description)}</div>
    </div>`;
  }
  if (mismatch && mismatch.mismatch) {
    html += `<div class="mtdna-preview-mismatch mtdna-mismatch-${mismatch.severity}">
      <strong>Environment mismatch:</strong> ${escapeHTML(mismatch.message)}
      ${mismatch.implications ? `<div class="mtdna-mismatch-implications">${escapeHTML(mismatch.implications)}</div>` : ''}
    </div>`;
  } else if (mismatch && !mismatch.mismatch) {
    html += `<div class="mtdna-preview-match">${escapeHTML(mismatch.message)}</div>`;
  }
  html += `</div>
  <div class="dna-preview-disclaimer">Processed locally. Coupling classification follows the Wallace mitochondrial paradigm — a research framework, not an established clinical standard.</div>
  <div class="dna-preview-actions">
    <button class="import-btn import-btn-secondary" onclick="window.closeMtDNAPreview()">Cancel</button>
    <button class="import-btn import-btn-primary" onclick="window.confirmMtDNAImport()">Import Haplogroup ${escapeHTML(resolved.haplogroup)}</button>
  </div>`;

  let overlay = document.getElementById('dna-modal-overlay');
  if (!overlay) {
    overlay = document.createElement('div');
    overlay.id = 'dna-modal-overlay';
    overlay.className = 'modal-overlay';
    document.body.appendChild(overlay);
  }
  overlay.innerHTML = `<div class="modal dna-preview-modal" role="dialog">${html}</div>`;
  overlay.classList.add('show');
}

export function closeMtDNAPreview() {
  const overlay = document.getElementById('dna-modal-overlay');
  if (overlay) overlay.classList.remove('show');
  window._pendingMtDNA = null;
}

export function confirmMtDNAImport() {
  const pending = window._pendingMtDNA;
  if (!pending) return;

  if (!state.importedData.genetics) {
    state.importedData.genetics = { source: null, importDate: null, coverage: { found: 0, total: 0 }, effects: {}, snps: {} };
  }
  state.importedData.genetics.mtdna = {
    haplogroup: pending.resolved.haplogroup,
    confidence: pending.resolved.confidence,
    coupling: pending.coupling ? {
      level: pending.coupling.level,
      label: pending.coupling.label,
      shortLabel: pending.coupling.shortLabel,
      climate: pending.coupling.climate,
      matchedLatBands: pending.coupling.matchedLatBands
    } : null,
    mutations: pending.mutations.map(m => m.raw),
    source: pending.source,
    importDate: new Date().toISOString().slice(0, 10)
  };

  saveImportedData();
  closeMtDNAPreview();
  showNotification(`Haplogroup ${pending.resolved.haplogroup} imported`, 'success');
  if (window.navigate) window.navigate('dashboard');
}

export function deleteMtDNAData() {
  if (state.importedData.genetics) {
    delete state.importedData.genetics.mtdna;
    saveImportedData();
    if (window.navigate) window.navigate('dashboard');
    showNotification('mtDNA haplogroup removed', 'info');
  }
}

// ═══════════════════════════════════════════════
// MANUAL HAPLOGROUP ENTRY
// ═══════════════════════════════════════════════

const HAPLOGROUP_LIST = ['A','B','C','D','E','F','G','H','HV','I','J','K','L0','L1','L2','L3','L4','L5','L6','M','N','R','T','U','V','W','X','Z'];

export async function setManualHaplogroup(haplogroup) {
  if (!haplogroup) return;
  const hg = haplogroup.toUpperCase().trim();
  if (!HAPLOGROUP_LIST.includes(hg)) {
    showNotification(`Unknown haplogroup "${hg}" — expected one of: ${HAPLOGROUP_LIST.join(', ')}`, 'error');
    return;
  }
  const hapTable = await loadHaplogroupTable();
  const coupling = classifyCoupling(hg, hapTable);
  if (!state.importedData.genetics) {
    state.importedData.genetics = { source: null, importDate: null, coverage: { found: 0, total: 0 }, effects: {}, snps: {} };
  }
  state.importedData.genetics.mtdna = {
    haplogroup: hg,
    confidence: 1,
    coupling: coupling ? {
      level: coupling.level,
      label: coupling.label,
      shortLabel: coupling.shortLabel,
      climate: coupling.climate,
      matchedLatBands: coupling.matchedLatBands
    } : null,
    mutations: [],
    source: 'manual',
    importDate: new Date().toISOString().slice(0, 10)
  };
  saveImportedData();
  showNotification(`Haplogroup ${hg} saved${coupling ? ' — ' + coupling.shortLabel : ''}`, 'success');
  if (window.navigate) window.navigate('dashboard');
}

export { HAPLOGROUP_LIST };

/// Inline-onclick confirm replacement. The genetics card's Delete link
/// used native window.confirm() which Electron strips; we dispatch to
/// the custom dialog instead.
function confirmDeleteDNA() {
  window.showConfirmDialog('Delete genetic data? This cannot be undone.', () => {
    deleteGeneticsData(window._getState().importedData);
    window._saveAndRefresh();
  });
}

// ═══════════════════════════════════════════════
// WINDOW EXPORTS
// ═══════════════════════════════════════════════
Object.assign(window, {
  isDNAFile,
  isDNAFileByContent,
  detectDNAFile,
  handleDNAFile,
  closeDNAImportPreview,
  confirmDNAImport,
  confirmDeleteDNA,
  deleteGeneticsData,
  toggleGeneticsCollapse,
  toggleGeneticsExpand,
  reimportDNA,
  handleMtDNAFile,
  closeMtDNAPreview,
  confirmMtDNAImport,
  deleteMtDNAData,
  detectMtDNAMismatch,
  ensureHaplogroupTable,
  setManualHaplogroup,
  HAPLOGROUP_LIST,
  _buildGeneticsContext: buildGeneticsContext,
  _getRelevantSNPs: getRelevantSNPs,
  _getState: () => state,
  _saveAndRefresh: () => { saveImportedData(); if (window.navigate) window.navigate('dashboard'); },
});
